// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC3lHMi3VwUUNJzSnVAd2VUTn-K7TQfHs',
    appId: '1:856997660335:web:608f7a028d7582fc7fb65a',
    messagingSenderId: '856997660335',
    projectId: 'islamic-lifestyle-muslim',
    authDomain: 'islamic-lifestyle-muslim.firebaseapp.com',
    storageBucket: 'islamic-lifestyle-muslim.appspot.com',
    measurementId: 'G-GHWVYQ1K8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArQFh1maFa3tHaSGRxcvWGdrBwjpOi3aY',
    appId: '1:856997660335:android:3af29a8eb9a6bb0f7fb65a',
    messagingSenderId: '856997660335',
    projectId: 'islamic-lifestyle-muslim',
    storageBucket: 'islamic-lifestyle-muslim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCifffLUjAHPEMH1VZPtY-7GxRt85MBuKU',
    appId: '1:856997660335:ios:4955f4ac81a9fe737fb65a',
    messagingSenderId: '856997660335',
    projectId: 'islamic-lifestyle-muslim',
    storageBucket: 'islamic-lifestyle-muslim.appspot.com',
    iosBundleId: 'com.sakib.islam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCifffLUjAHPEMH1VZPtY-7GxRt85MBuKU',
    appId: '1:856997660335:ios:4b08c6ad13063d2e7fb65a',
    messagingSenderId: '856997660335',
    projectId: 'islamic-lifestyle-muslim',
    storageBucket: 'islamic-lifestyle-muslim.appspot.com',
    iosBundleId: 'com.sakib.sakib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC3lHMi3VwUUNJzSnVAd2VUTn-K7TQfHs',
    appId: '1:856997660335:web:2971ef95f89c181f7fb65a',
    messagingSenderId: '856997660335',
    projectId: 'islamic-lifestyle-muslim',
    authDomain: 'islamic-lifestyle-muslim.firebaseapp.com',
    storageBucket: 'islamic-lifestyle-muslim.appspot.com',
    measurementId: 'G-T3KZ1HVVJS',
  );
}
