name: sakib

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  intl: ^0.20.2
  adhan: ^2.0.0+1
  hijri: ^3.0.0
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  table_calendar: ^3.1.1
  flutter_svg: ^2.0.10+1
  just_audio: ^0.9.38
  permission_handler: ^11.3.1
  flutter_qiblah: ^3.0.3
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.9.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.0
  android_intent_plus: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
